version: '3.7'

services:
  web:
    build: .
    command: python /ch4-message-board-app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ch4-message-board-app
    ports:
      - 8000:8000
    env_file: .env
